version: 2
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: banian/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "package.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      # Test
      - run:
          name: Tests
          command: yarn test
      
      # Build
      - run:
          name: Build
          command: |
            yarn generate-demo

      # Deploy
      - deploy:
          name: Surge
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn surge
            fi
